# Generated by Django 4.2.3 on 2023-07-13 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 20, 50, 9, 86946, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
